#!/bin/bash
VAR=~/.i3/secondary_state
PRIMARY_CONNECTOR="DP-1"
SECONDARY_CONNECTOR="DP-2"
LVDSDPI=96
HDMIDPI=$LVDSPI
source $VAR

if xrandr -q | grep -q "${SECONDARY_CONNECTOR} connected"; then
   if [ ${STATE} == off ]; then
      xrandr --output ${SECONDARY_CONNECTOR} --auto --noprimary --same-as ${PRIMARY_CONNECTOR} --primary --dpi $LVDSDPI
      echo STATE=same > $VAR
   elif [ ${STATE} == same ]; then
      xrandr --output ${SECONDARY_CONNECTOR} --auto --noprimary --right-of ${PRIMARY_CONNECTOR} --primary --dpi $LVDSDPI
      echo STATE=right > $VAR
   elif [ ${STATE} == right ]; then
      xrandr --output ${SECONDARY_CONNECTOR} --off --output ${PRIMARY_CONNECTOR} --primary --dpi $LVDSDPI
      echo STATE=off > $VAR
   fi
else xrandr -q | grep -q "${SECONDARY_CONNECTOR} disconnected";
   xrandr --output ${SECONDARY_CONNECTOR} --off --output ${PRIMARY_CONNECTOR} --primary --dpi $LVDSDPI
   echo STATE=off > $VAR
fi

#source hdmi
#echo ${STATE}
