" All system-wide defaults are set in $VIMRUNTIME/archlinux.vim (usually just
" /usr/share/vim/vimfiles/archlinux.vim) and sourced by the call to :runtime
" you can find below.  If you wish to change any of those settings, you should
" do it in this file (/etc/vimrc), since archlinux.vim will be overwritten
" everytime an upgrade of the vim packages is performed.  It is recommended to
" make changes after sourcing archlinux.vim since it alters the value of the
" 'compatible' option.

" This line should not be removed as it ensures that various options are
" properly set to work with the Vim-related packages.
runtime! archlinux.vim

" If you prefer the old-style vim functionalty, add 'runtime! vimrc_example.vim'
" Or better yet, read /usr/share/vim/vim74/vimrc_example.vim or the vim manual
" and configure vim to your own liking!

"
" Eigene Einträge...
"

"Blendet links die Zeilennummern ein"
set number

"Schalte Syntaxhighlighting ein
syntax on

"Einrueckung der vorherigen Zeile erhalten"
set autoindent

"Zeigt die Kommandos im Kommandmodus an."
set showcmd

" ":autocmd" ":shell" ":write" in Konf.dateien im akt. Verz. NICHT erlaubt (DO!)
" sowie Map-Kommandos anzeigen (insbesondere falls 'exrc' gesetzt!)
" set secure

" Editmodus-Anzeige in Statuszeile links unten (DO!)
" (-- EINFÜGEN --, -- VISUELL ... --, -- ERSETZEN --)
set showmode

" Koordinatenanzeige in Statuszeile aktivieren (DO!)
" (SET 'paste' -> 'noruler')
set ruler

" Bei 'wrap' Zeilen statt im Wort am Zl.ende nur an "schönen" Stellen umbrechen
" (nur Darstellung, es wird NICHT wirklich umgebrochen!)
set linebreak

" Auswahl der Zeichen, bei denen mit "'linbreak' bei 'wrap' umgebrochen wird
" (Leerzeichen schützen: "\ "!)
set breakat=\ ^I!@*-+;:,./?"

" Während Eingabe eines Suchmusters bereits suchen (inkrementell)
" Alle zu einem Suchmuster passenden Textstücke markieren (highlight)
" (:nohlsearch 'invhls' schaltet Markierungen, 'invhls' invertiert sie!)
" :highlight IncSearch term=reverse cterm=reverse
" :highlight Search    term=reverse ctermfg=0 ctermbg=3
set incsearch
"set hlsearch

" GROSS/kleinschreibung bei Suche NICHT beachten
" (ABSCHALTEN mit \C, EINSCHALTEN mit \c im Suchmuster = case!)
" ('smartcase' -> außer Grossbuchstabe kommt im Suchmuster vor, z.B.
"  SmartCase, SMARTcase, smartCASE, SmArTcAsE, sMaRtCaSe, smartcase)
set ignorecase
set smartcase


